//  MultiPartIOSDemoAPIClient.h
//
//  Generated by the the JBoss AeroGear Xcode Project Template on 9/12/13.
//  See Project's web site for more details http://www.aerogear.org
//

#import "AeroGear.h"

@interface MultiPartIOSDemoAPIClient : NSObject

// the pipes for this service
@property(readonly, nonatomic) id<AGPipe> uploadPipe;

+ (MultiPartIOSDemoAPIClient *)sharedInstance;

@end